### ISSUE TITLE
docker is not working

### ISSUE THREAD

**Issue by 9cat** [CoNET-project/conet-platform-docker#1]
conet-platform-docker# docker logs -f conet-platform-docker-conet-platform-local-1
exec /usr/local/bin/docker-entrypoint.sh: exec format error

AMD64

**Comment by CoNETProject** [comment]
This issue was CONET platform docker image only support arm64.

Fix: added amd64 support
```
docker buildx build --push --platform linux/amd64, linux/arm64 --tag conetnetwork/conet:platform .
```

Build Multi-Architecture Images!
