### ISSUE TITLE
Docker not working

### ISSUE THREAD

**Issue by Lanroc** [CoNET-project/conet-platform-docker#2]
lanroc@DESKTOP-HU306E1:~/conet/conet-platform-docker/conet-platform-docker$ docker logs conet-platform-docker-conet-platform-local-1 -f
exec /usr/local/bin/docker-entrypoint.sh: exec format error

intel x64

**Comment by CoNETProject** [comment]
Thanks.
Could you more detail about your OS. I can't repeat that issue in my laptop with x64 & MacOS

**Comment by CoNETProject** [comment]
I rebuild the docker image. could you pull the image & run again
```
docker image pull conetnetwork/conet:platform
docker-compose up -d
```

**Comment by Lanroc** [comment]
fixed
lanroc@DESKTOP-HU306E1:~/conet/conet-platform-docker/conet-platform-docker$ docker logs conet-platform-docker-conet-platform-local-1 -f
 [Seguro-worker INFO 19:46:46:40] /seguro-platform/build
┌─────────┬─────────────────────────────────────────────────────────────────────────────────────────────────┐
│ (index) │                                       Kloak Local Server                                        │
├─────────┼─────────────────────────────────────────────────────────────────────────────────────────────────┤
│    0    │ 'http://localhost:3001, local-path = [/usr/src/workers] staticFolder1 [/seguro-platform/build]' │
└─────────┴─────────────────────────────────────────────────────────────────────────────────────────────────┘

**Comment by CoNETProject** [comment]
Thank you [Lanroc](https://github.com/Lanroc)
